

export enum KalturaRuleActionType {
    allowPlayback = 'ALLOW_PLAYBACK',
	applyDiscountModule = 'APPLY_DISCOUNT_MODULE',
	applyFreePlayback = 'APPLY_FREE_PLAYBACK',
	applyPlaybackAdapter = 'APPLY_PLAYBACK_ADAPTER',
	assetLifeCycleTransition = 'ASSET_LIFE_CYCLE_TRANSITION',
	block = 'BLOCK',
	blockPlayback = 'BLOCK_PLAYBACK',
	endDateOffset = 'END_DATE_OFFSET',
	filter = 'FILTER',
	filterassetbyksql = 'FilterAssetByKsql',
	filterfilebyaudiocodecindiscovery = 'FilterFileByAudioCodecInDiscovery',
	filterfilebyaudiocodecinplayback = 'FilterFileByAudioCodecInPlayback',
	filterfilebyfiletypeidforassettypeindiscovery = 'FilterFileByFileTypeIdForAssetTypeInDiscovery',
	filterfilebyfiletypeidforassettypeinplayback = 'FilterFileByFileTypeIdForAssetTypeInPlayback',
	filterfilebyfiletypeidindiscovery = 'FilterFileByFileTypeIdInDiscovery',
	filterfilebyfiletypeidinplayback = 'FilterFileByFileTypeIdInPlayback',
	filterfilebylabelindiscovery = 'FilterFileByLabelInDiscovery',
	filterfilebylabelinplayback = 'FilterFileByLabelInPlayback',
	filterfilebyqualityindiscovery = 'FilterFileByQualityInDiscovery',
	filterfilebyqualityinplayback = 'FilterFileByQualityInPlayback',
	filterfilebystreamertypeindiscovery = 'FilterFileByStreamerTypeInDiscovery',
	filterfilebystreamertypeinplayback = 'FilterFileByStreamerTypeInPlayback',
	filterfilebyvideocodecindiscovery = 'FilterFileByVideoCodecInDiscovery',
	filterfilebyvideocodecinplayback = 'FilterFileByVideoCodecInPlayback',
	startDateOffset = 'START_DATE_OFFSET',
	userBlock = 'USER_BLOCK'
}